spring.application.name=bookingsystem
server.port=8080

spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=bookingsystemapp
spring.mongodb.authentication-database=admin
