spring.application.name=bookingsystem
server.port=8080

spring.mongodb.username=root
spring.mongodb.password=root
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=bookingsystemapp
spring.mongodb.authentication-database=admin

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.com.example.instructorapi=INFO

app.jwt.secret=8xuD80BSoAus/+IpU/bSxeP1cfv3g47iLszq6Y/+XRM=
app.jwt.expiration-ms=36000000

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

admin.secret=SUPER-ADMIN-SECRET
